package types

var FirstWorld = World{
	[]Tile{
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Grass, Grass, Grass, Water, Water, Grass, Grass, Water, Water,
		Water, Grass, Grass, Grass, Grass, Water, Water, Grass, Grass, Water,
		Water, Grass, Grass, Grass, Grass, Grass, Water, Grass, Grass, Water,
		Water, Water, Water, Water, Grass, Grass, Water, Grass, Grass, Water,
		Water, Water, Grass, Grass, Grass, Water, Water, Grass, Grass, Water,
		Water, Grass, Grass, Grass, Water, Water, Grass, Grass, Grass, Water,
		Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water,
		Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water,
	},
	10, 10,
}

var Test4x4World = World{
	[]Tile{
		Water, Water, Water, Water,
		Water, Grass, Grass, Water,
		Water, Grass, Grass, Water,
		Water, Water, Water, Water,
	},
	4, 4,
}

var BigWorld = World{
	[]Tile{
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Water, Water, Water, Water, Water, Water, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water,
		Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water,
		Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water,
		Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water,
		Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Grass, Grass, Water, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water,
		Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water,
		Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Grass, Water, Water, Water,
		Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Grass, Grass, Water, Water,
		Water, Water, Water, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Grass, Grass, Water, Water,
		Water, Water, Water, Grass, Grass, Grass, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water,
		Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water,
		Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water,
		Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Water, Water, Water,
		Water, Water, Water, Water, Water, Grass, Grass, Grass, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Water, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Grass, Grass, Water, Water, Water, Water, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Grass, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water,
		Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water, Water,
	},
	40, 40,
}
